final List<String> titleStore = [
  'عروض التوصيل',
  'مطاعم ',
  'عصائر ',
  'سوبر ماركت ',
  'حلويات',
  'صيدليات',
  'رسلني الخير ',
  'بطاقات رقمية ',
  'خدمات مرسول ',
  'كافيهات  ',
  'هدايا وورود',
  'مخابز',
  'احتياجات المنزل ',
  'الأسر المنتجة ',
  'الدكان ',
  'إلكترونيات  ',
  'الجمال والموضة',
  'مكتبات',
  'محامص ',
  'صحي ',
  'المنتجات العضوية ',
];
final List<String> typesTitle = [
  'عروض ',
  'الأطباق الرئيسية عادية ',
  'الأطباق الرئيسية صغير ',
  'وجبات الرشاقة ',
  'الأطباق الجانبية',
  'المشروبات',
];
final List<String> subTitleStore = [
  'قائمة عروض التوصيل',
  'قائمة مطاعم ',
  'قائمة عصائر ',
  'قائمة سوبر ماركت ',
  'قائمة حلويات',
  'قائمة صيدليات',
  'قائمة رسلني الخير ',
  'قائمة بطاقات رقمية ',
  'قائمة خدمات مرسول ',
  'قائمة كافيهات  ',
  'قائمة هدايا وورود',
  'قائمة مخابز',
  'قائمة احتياجات المنزل ',
  'قائمة الأسر المنتجة ',
  'قائمة الدكان ',
  'قائمة إلكترونيات  ',
  'قائمة الجمال والموضة',
  'قائمة مكتبات',
  'قائمة محامص ',
  'قائمة صحي ',
  'قائمة المنتجات العضوية ',
];

final List<dynamic> listwidget = ['قائمة عروض التوصيل'];
List<String> imageList = [
  'assets/services/offer.png',
  'assets/services/restaurant.jpg',
  'assets/services/juice.png',
  'assets/services/market.png',
  'assets/services/sweet.png',
  'assets/services/pharmacy.png',
  'assets/services/charity.png',
  'assets/services/card-digit.png',
  'assets/services/service.png',
  'assets/services/coffee.png',
  'assets/services/gifts.png',
  'assets/services/backery.png',
  'assets/services/tool.png',
  'assets/services/hand-made.png',
  'assets/services/dekan.png',
  'assets/services/electro.png',
  'assets/services/perfume.png',
  'assets/services/pen.png',
  'assets/services/coffee22.png',
  'assets/services/healthy.png',
  'assets/services/organic.png',
];

final List<String> additionMeal = [
  'إختار وشكلها ',
  'أضف المزيد من المقبلات ',
];
const String apiKey = "AIzaSyAq8f4RU1a0qR-l2ybz8qkv29YjZqw04QA";