final List<String> itemCategory = [
  'عروض التوصيل',
  'مطاعم ',
  'عصائر ',
  'سوبر ماركت ',
  'حلويات',
  'صيدليات',
  'رسلني الخير ',
  'بطاقات رقمية ',
  'خدمات مرسول ',
  'كافيهات  ',
  'هدايا وورود',
  'مخابز',
  'احتياجات المنزل ',
  'الأسر المنتجة ',
  'الدكان ',
  'إلكترونيات  ',
  'الجمال والموضة',
  'مكتبات',
  'محامص ',
  'صحي ',
  'المنتجات العضوية ',
];

final List<dynamic> listwidget = ['قائمة عروض التوصيل'];
List<String> imageList = [
  'assets/services/offer.png',
  'assets/services/restaurant.jpg',
  'assets/services/juice.png',
  'assets/services/market.png',
  'assets/services/sweet.png',
  'assets/services/pharmacy.png',
  'assets/services/charity.png',
  'assets/services/card-digit.png',
  'assets/services/service.png',
  'assets/services/coffee.png',
  'assets/services/gifts.png',
  'assets/services/backery.png',
  'assets/services/tool.png',
  'assets/services/hand-made.png',
  'assets/services/dekan.png',
  'assets/services/electro.png',
  'assets/services/perfume.png',
  'assets/services/pen.png',
  'assets/services/coffee22.png',
  'assets/services/healthy.png',
  'assets/services/organic.png',
];
